
import static com.sun.org.apache.bcel.internal.classfile.Utility.format;
import static java.lang.String.format;
import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.*;
import java.awt.List;
import static java.lang.String.format;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author denis
 */

import static java.lang.String.format;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Calendar;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;
import static org.sqlite.date.DateFormatUtils.format;
public class Sewa extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form Sewa
     */
    DefaultTableModel defaultTableModel = new DefaultTableModel();

    public Sewa() {
        initComponents();
        conn=Connect.getConnect();
        setLocationRelativeTo(null);
        updatecombo();
        
        Object columns[] = {"Nama","Studio","Tanggal","Jam Mulai","Jam Selesai","Status"};
        defaultTableModel.setColumnIdentifiers(columns);
        table_data_sewa.setModel(defaultTableModel); 
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        dateChooserPanel1 = new datechooser.beans.DateChooserPanel();
        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmd_simpan = new javax.swing.JButton();
        Date date = new Date();
        SpinnerDateModel sm =
        new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        jam_sewa = new javax.swing.JSpinner(sm);
        jLabel6 = new javax.swing.JLabel();
        cmb_studio = new javax.swing.JComboBox<>();
        cmd_kembali = new javax.swing.JButton();
        // Code adding the component to the parent container - not shown here
        Date date2 = new Date();
        SpinnerDateModel se =
        new SpinnerDateModel(date2, null, null, Calendar.HOUR_OF_DAY);
        jam_kembali = new javax.swing.JSpinner(se);
        cmb_nama = new javax.swing.JComboBox<>();
        Tgl = new com.toedter.calendar.JCalendar();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_data_sewa = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tanggal");

        jLabel2.setText("Nama");

        jLabel4.setText("Waktu");

        jLabel5.setText("Studio");

        cmd_simpan.setText("Simpan");
        cmd_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_simpanActionPerformed(evt);
            }
        });

        JSpinner.DateEditor de = new JSpinner.DateEditor(jam_sewa, "HH:mm");
        jam_sewa.setEditor(de);

        jLabel6.setText("-");

        cmb_studio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Studio 1", "Studio 2" }));

        cmd_kembali.setText("Kembali");
        cmd_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_kembaliActionPerformed(evt);
            }
        });

        JSpinner.DateEditor ab = new JSpinner.DateEditor(jam_kembali, "HH:mm");
        jam_kembali.setEditor(ab);

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setText("Batal");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        table_data_sewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        table_data_sewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_data_sewaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_data_sewa);

        jButton1.setText("Selesai");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("ID Pemesanan");

        id.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("SEWA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmb_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jam_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jam_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmb_studio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmd_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmd_kembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(Tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmb_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmd_simpan)
                            .addComponent(update))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jam_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jam_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete)
                            .addComponent(cmd_kembali))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmb_studio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(Tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_simpanActionPerformed
        // TODO add your handling code here:
        String nama = cmb_nama.getSelectedItem().toString();
        
        pengecekkanSewa(nama);
        
    }//GEN-LAST:event_cmd_simpanActionPerformed

    
    private void cmd_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_kembaliActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmd_kembaliActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
            String nama = cmb_nama.getSelectedItem().toString();
            String value=cmb_studio.getSelectedItem().toString();
            
            java.util.Date date = Tgl.getDate();
            DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            String coba = format.format(date).toString();
        
            Date date1 = (Date)jam_sewa.getValue();
            DateFormat format1 = new SimpleDateFormat("HH:mm");
            String coba1 = format1.format(date1).toString();
            
            Date date2 = (Date)jam_kembali.getValue();
            DateFormat format2 = new SimpleDateFormat("HH:mm");
            String coba2 = format2.format(date2).toString();
        try{
            

            String value1= nama;
            String value2= value;
            String value3= coba;
            String value4= coba1;
            String value5= coba2;
            
            String sql = "update Sewa set Nama='"+value1+"',Studio='"+value2+"',Tgl='"+value3+"',waktu_sewa='"+value4+"',waktu_sel='"+value5+"' where Nama='"+value1+"'";
            pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Updated");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void table_data_sewaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_data_sewaMouseClicked
        // TODO add your handling code here:
        
        
        try{
            int row = table_data_sewa.getSelectedRow();
            String Table_click = (table_data_sewa.getModel().getValueAt(row, 0).toString());
            String sql = "select * from Sewa where Nama='"+Table_click+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            if(rs.next()){
                String add1 = rs.getString("Nama");
                cmb_nama.setSelectedItem(add1);
                String add2 = rs.getString("Studio");
                cmb_studio.setSelectedItem(add2);
                
                String add3 = rs.getString("Tgl");
                DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                Date date = format.parse(add3);
                Tgl.setDate(date);
                
                String add4 = rs.getString("waktu_sewa");
                DateFormat format2 = new SimpleDateFormat("HH:mm");
                Date date2 = format2.parse(add4);
                jam_sewa.setValue(date2);
                
                String add5 = rs.getString("waktu_sel");
                DateFormat format3 = new SimpleDateFormat("HH:mm");
                Date date3 = format3.parse(add5);
                jam_kembali.setValue(date3);
                
                String add6 = rs.getString("id");
                id.setText(add6);
                
                table_data_sewa.removeAll();
                
                
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_table_data_sewaMouseClicked
    
    
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String sql ="delete from Sewa where id =?";
        try{
            
            pst=conn.prepareStatement(sql);
            
            pst.setString(1, id.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil di Hapus");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        loadData();
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nama = cmb_nama.getSelectedItem().toString();
        delete(nama);
        new History().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void delete(String Nama){
            try{
            Connection conn = Connect.getConnect();
            String sql = "INSERT INTO History(Nama,Studio,Tgl,waktu_sewa,waktu_sel) VALUES(?,?,?,?,?)";
            
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1,Nama);
            
            String value=cmb_studio.getSelectedItem().toString();
            stmt.setString(2,value);
            
            java.util.Date date = Tgl.getDate();
            DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            String coba = format.format(date).toString();
            stmt.setString(3,coba);
            
            Date date1 = (Date)jam_sewa.getValue();
            DateFormat format1 = new SimpleDateFormat("HH:mm");
            String coba1 = format1.format(date1).toString();
            stmt.setString(4,coba1);
            
            Date date2 = (Date)jam_kembali.getValue();
            DateFormat format2 = new SimpleDateFormat("HH:mm");
            String coba2 = format2.format(date2).toString();
            stmt.setString(5,coba2);
            stmt.executeUpdate();
            
            
        }catch(Exception e){
            System.out.println(e);
        }
        
    
        
        String sql ="delete from Sewa where id =?";
        try{
            
            pst=conn.prepareStatement(sql);
            
            pst.setString(1, id.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Waktu Telah selesai");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        loadData();
    }
    
    private void updatecombo(){
        String sql = "Select * from Member";
        try{
            pst= conn.prepareStatement(sql);
            rs= pst.executeQuery();
            while(rs.next()){
                cmb_nama.addItem(rs.getString("Nama"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);  
        }
    }
    
    public void pengecekkanSewa(String Nama){
        Connection conn = Connect.getConnect();                
        try{
            String sql = "select Nama from Sewa";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            
                insertUserToDatabase(Nama);
        
        }catch(Exception e){
            System.out.println(e);
            
        }
            
    }
    
    
    public SimpleDateFormat yourDate = new SimpleDateFormat("MM-dd-yyyy");
    
    public void insertUserToDatabase(String Nama) throws ParseException{
          
        try{
            Connection conn = Connect.getConnect();
            String sql = "INSERT INTO Sewa(Nama,Studio,Tgl,waktu_sewa,waktu_sel) VALUES(?,?,?,?,?)";
            
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1,Nama);
            
            String value=cmb_studio.getSelectedItem().toString();
            stmt.setString(2,value);
            
            java.util.Date date = Tgl.getDate();
            DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            String coba = format.format(date).toString();
            stmt.setString(3,coba);
            
            Date date1 = (Date)jam_sewa.getValue();
            DateFormat format1 = new SimpleDateFormat("HH:mm");
            String coba1 = format1.format(date1).toString();
            stmt.setString(4,coba1);
            
            Date date2 = (Date)jam_kembali.getValue();
            DateFormat format2 = new SimpleDateFormat("HH:mm");
            String coba2 = format2.format(date2).toString();
            stmt.setString(5,coba2);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Berhasil terdaftar");
            
            
        }catch(Exception e){
            System.out.println(e);
        }
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sewa().setVisible(true);
            }
        });
    }
    
        public void loadData(){
        conn = Connect.getConnect();
        if(conn != null){
            String sql = "Select Nama,Studio,Tgl,Waktu_sewa,Waktu_sel from Sewa";
            try{
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                Object[] columnData = new Object [6];
                while(rs.next()){
                    columnData[0] = rs.getString("Nama");
                    columnData[1] = rs.getString("Studio");
                    columnData[2] = rs.getString("Tgl");
                    columnData[3] = rs.getString("Waktu_sewa");
                    columnData[4] = rs.getString("Waktu_sel");      
                   //columnData[5] = rs.getString("");
                    defaultTableModel.addRow(columnData);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);  
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar Tgl;
    private javax.swing.JComboBox<String> cmb_nama;
    private javax.swing.JComboBox<String> cmb_studio;
    private javax.swing.JButton cmd_kembali;
    private javax.swing.JButton cmd_simpan;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private datechooser.beans.DateChooserPanel dateChooserPanel1;
    private javax.swing.JButton delete;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JSpinner jam_kembali;
    private javax.swing.JSpinner jam_sewa;
    private javax.swing.JTable table_data_sewa;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
